# Site settings
title: Freelancer
email: your-email@domain.com
url: https://github.com/jeromelachaud/freelancer-theme
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "machine learning, ML, artificial intelligence, AI, software engineering, software development, SWE, biomedical engineering, biomedical, engineer, BME, university of waterloo, waterloo, UW, 2021, internship, coop"
skills: "Machine Learning - Software Development - Biomedical Design"
meta_author: Chen Grace

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: f73chen

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: b836ff #80B3FF
  primary-rgb: "184, 54, 255" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Grace Chen
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/f73chen/
  - title: github
    url: https://github.com/f73chen
  - title: facebook
    url: https://www.facebook.com/xaeque/

# Postal address (add as many lines as necessary)
address:
  - line: 1710-89 Dunfield Ave.
  - line: Toronto, ON, M4S 0A4

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
